server:
  addr: "127.0.0.1:80"
  name: "project_api"
zap:
  debugFileName: "D:\\go_project\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName:  "D:\\go_project\\ms_project\\logs\\info\\project-info.log"
  warnFileName:  "D:\\go_project\\ms_project\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"
