server:
  addr: "127.0.0.1:8081"
  name: "project_project"
zap:
  debugFileName: "D:\\go_project\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName:  "D:\\go_project\\ms_project\\logs\\info\\project-info.log"
  warnFileName:  "D:\\go_project\\ms_project\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
grpc:
    addr: "127.0.0.1:8882"
    name: "project"
    version: "1.0.0"
    weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject
db:
  separation: false
  master:
    name: master
    username: root
    password: root
    host: 127.0.0.1
    port: 3309
    db: msproject
  slave:
    - username: root
      password: root
      host: 127.0.0.1
      port: 3310
      db: msproject
      name: slave1
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_project